# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_job import AppJob

class TestAppJob(unittest.TestCase):
    """AppJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppJob:
        """Test AppJob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppJob`
        """
        model = AppJob()
        if include_optional:
            return AppJob(
                id = 56,
                job_name = '',
                user_id = '',
                app_id = '',
                app_name = '',
                instance_name = '',
                cpod_id = '',
                status = '',
                billing_status = 56,
                url = '',
                start_time = '',
                end_time = '',
                created_at = '',
                updated_at = ''
            )
        else:
            return AppJob(
                id = 56,
                job_name = '',
                user_id = '',
                app_id = '',
                app_name = '',
                instance_name = '',
                cpod_id = '',
                status = '',
                billing_status = 56,
                url = '',
                start_time = '',
                end_time = '',
                created_at = '',
                updated_at = '',
        )
        """

    def testAppJob(self):
        """Test AppJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
