# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.balance_add_resp import BalanceAddResp

class TestBalanceAddResp(unittest.TestCase):
    """BalanceAddResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BalanceAddResp:
        """Test BalanceAddResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BalanceAddResp`
        """
        model = BalanceAddResp()
        if include_optional:
            return BalanceAddResp(
                message = ''
            )
        else:
            return BalanceAddResp(
                message = '',
        )
        """

    def testBalanceAddResp(self):
        """Test BalanceAddResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
