# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_recharge import UserRecharge

class TestUserRecharge(unittest.TestCase):
    """UserRecharge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserRecharge:
        """Test UserRecharge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserRecharge`
        """
        model = UserRecharge()
        if include_optional:
            return UserRecharge(
                id = 56,
                recharge_id = '',
                user_id = '',
                amount = 1.337,
                before_balance = 1.337,
                after_balance = 1.337,
                description = '',
                created_at = '',
                updated_at = ''
            )
        else:
            return UserRecharge(
                id = 56,
                recharge_id = '',
                user_id = '',
                amount = 1.337,
                before_balance = 1.337,
                after_balance = 1.337,
                description = '',
                created_at = '',
                updated_at = '',
        )
        """

    def testUserRecharge(self):
        """Test UserRecharge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
