# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.resource import Resource

class TestResource(unittest.TestCase):
    """Resource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Resource:
        """Test Resource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Resource`
        """
        model = Resource()
        if include_optional:
            return Resource(
                id = '',
                name = '',
                object = '',
                owner = '',
                size = 56,
                is_public = True,
                user_id = '',
                tag = [
                    ''
                    ],
                template = '',
                meta = '',
                category = '',
                base_model = '',
                finetune_gpu_count = 56,
                inference_gpu_count = 56
            )
        else:
            return Resource(
                id = '',
                name = '',
                object = '',
                owner = '',
                size = 56,
                is_public = True,
                user_id = '',
                tag = [
                    ''
                    ],
                template = '',
                meta = '',
                category = '',
                base_model = '',
                finetune_gpu_count = 56,
                inference_gpu_count = 56,
        )
        """

    def testResource(self):
        """Test Resource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
