# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.scheduler_api_api import SchedulerApiApi


class TestSchedulerApiApi(unittest.TestCase):
    """SchedulerApiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SchedulerApiApi()

    def tearDown(self) -> None:
        pass

    def test_app_job_add(self) -> None:
        """Test case for app_job_add

        创建应用
        """
        pass

    def test_app_job_delete(self) -> None:
        """Test case for app_job_delete

        终止应用
        """
        pass

    def test_app_job_get(self) -> None:
        """Test case for app_job_get

        查询应用
        """
        pass

    def test_app_list(self) -> None:
        """Test case for app_list

        应用查询接口
        """
        pass

    def test_app_register(self) -> None:
        """Test case for app_register

        应用注册接口
        """
        pass

    def test_app_unregister(self) -> None:
        """Test case for app_unregister

        应用注销接口
        """
        pass

    def test_balance_add(self) -> None:
        """Test case for balance_add

        余额充值
        """
        pass

    def test_balance_get(self) -> None:
        """Test case for balance_get

        余额查询
        """
        pass

    def test_base_image_list(self) -> None:
        """Test case for base_image_list

        基础镜像列表
        """
        pass

    def test_billing_list(self) -> None:
        """Test case for billing_list

        账单明细
        """
        pass

    def test_billing_tasks(self) -> None:
        """Test case for billing_tasks

        聚合账单
        """
        pass

    def test_cluster_cpods(self) -> None:
        """Test case for cluster_cpods

        集群列表
        """
        pass

    def test_cpod_job_handler(self) -> None:
        """Test case for cpod_job_handler

        """
        pass

    def test_cpod_status_handler(self) -> None:
        """Test case for cpod_status_handler

        """
        pass

    def test_create_new_user_id(self) -> None:
        """Test case for create_new_user_id

        生成所有user_id
        """
        pass

    def test_dingtalk_callback(self) -> None:
        """Test case for dingtalk_callback

        钉钉回调
        """
        pass

    def test_dingtalk_userinfo(self) -> None:
        """Test case for dingtalk_userinfo

        钉钉用户信息
        """
        pass

    def test_finetune_handler(self) -> None:
        """Test case for finetune_handler

        """
        pass

    def test_gpu_type_handler(self) -> None:
        """Test case for gpu_type_handler

        """
        pass

    def test_inference_delete_handler(self) -> None:
        """Test case for inference_delete_handler

        """
        pass

    def test_inference_deploy_handler(self) -> None:
        """Test case for inference_deploy_handler

        """
        pass

    def test_inference_info_handler(self) -> None:
        """Test case for inference_info_handler

        """
        pass

    def test_inference_stop_handler(self) -> None:
        """Test case for inference_stop_handler

        """
        pass

    def test_job_create_handler(self) -> None:
        """Test case for job_create_handler

        """
        pass

    def test_job_get_handler(self) -> None:
        """Test case for job_get_handler

        """
        pass

    def test_job_status_handler(self) -> None:
        """Test case for job_status_handler

        """
        pass

    def test_job_stop_handler(self) -> None:
        """Test case for job_stop_handler

        """
        pass

    def test_jobs_del(self) -> None:
        """Test case for jobs_del

        终止用户所有任务
        """
        pass

    def test_jupyterlab_create(self) -> None:
        """Test case for jupyterlab_create

        创建jupyterlab实例
        """
        pass

    def test_jupyterlab_del(self) -> None:
        """Test case for jupyterlab_del

        删除jupyterlab实例
        """
        pass

    def test_jupyterlab_image_create(self) -> None:
        """Test case for jupyterlab_image_create

        构建镜像
        """
        pass

    def test_jupyterlab_image_del(self) -> None:
        """Test case for jupyterlab_image_del

        删除镜像
        """
        pass

    def test_jupyterlab_image_list(self) -> None:
        """Test case for jupyterlab_image_list

        镜像列表
        """
        pass

    def test_jupyterlab_image_version_list(self) -> None:
        """Test case for jupyterlab_image_version_list

        镜像版本列表
        """
        pass

    def test_jupyterlab_list(self) -> None:
        """Test case for jupyterlab_list

        查询jupyterlab实例列表
        """
        pass

    def test_jupyterlab_pause(self) -> None:
        """Test case for jupyterlab_pause

        暂停jupyterlab实例
        """
        pass

    def test_jupyterlab_resume(self) -> None:
        """Test case for jupyterlab_resume

        恢复jupyterlab实例
        """
        pass

    def test_jupyterlab_update(self) -> None:
        """Test case for jupyterlab_update

        更新jupyterlab实例
        """
        pass

    def test_node_add_handler(self) -> None:
        """Test case for node_add_handler

        """
        pass

    def test_node_list_handler(self) -> None:
        """Test case for node_list_handler

        """
        pass

    def test_oss_sync(self) -> None:
        """Test case for oss_sync

        oss资源同步
        """
        pass

    def test_quota_add_handler(self) -> None:
        """Test case for quota_add_handler

        """
        pass

    def test_quota_delete_handler(self) -> None:
        """Test case for quota_delete_handler

        """
        pass

    def test_quota_list_handler(self) -> None:
        """Test case for quota_list_handler

        """
        pass

    def test_quota_update_handler(self) -> None:
        """Test case for quota_update_handler

        """
        pass

    def test_recharge_list(self) -> None:
        """Test case for recharge_list

        充值记录
        """
        pass

    def test_register(self) -> None:
        """Test case for register

        用户注册
        """
        pass

    def test_resource_adapters_handler(self) -> None:
        """Test case for resource_adapters_handler

        适配器列表
        """
        pass

    def test_resource_datasets_handler(self) -> None:
        """Test case for resource_datasets_handler

        数据集列表
        """
        pass

    def test_resource_load_handler(self) -> None:
        """Test case for resource_load_handler

        创建资源同步任务
        """
        pass

    def test_resource_meta_add(self) -> None:
        """Test case for resource_meta_add

        新增数据资产信息
        """
        pass

    def test_resource_meta_del(self) -> None:
        """Test case for resource_meta_del

        删除数据资产信息
        """
        pass

    def test_resource_models_handler(self) -> None:
        """Test case for resource_models_handler

        模型列表
        """
        pass

    def test_resource_task_get(self) -> None:
        """Test case for resource_task_get

        获取资源同步任务
        """
        pass

    def test_resource_task_status(self) -> None:
        """Test case for resource_task_status

        查询资源同步任务状态
        """
        pass

    def test_resource_task_update(self) -> None:
        """Test case for resource_task_update

        更新资源同步任务
        """
        pass

    def test_send_email(self) -> None:
        """Test case for send_email

        发送邮件验证码
        """
        pass

    def test_upload_status_handler(self) -> None:
        """Test case for upload_status_handler

        """
        pass

    def test_uploader_access_handler(self) -> None:
        """Test case for uploader_access_handler

        """
        pass

    def test_user_info(self) -> None:
        """Test case for user_info

        """
        pass

    def test_user_list_handler(self) -> None:
        """Test case for user_list_handler

        """
        pass

    def test_user_login(self) -> None:
        """Test case for user_login

        """
        pass


if __name__ == '__main__':
    unittest.main()
