# coding: utf-8

"""
    SDK

    算想云对开发者提供的API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.scheduler_api_api import SchedulerApiApi


class TestSchedulerApiApi(unittest.TestCase):
    """SchedulerApiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SchedulerApiApi()

    def tearDown(self) -> None:
        pass

    def test_finetune_handler(self) -> None:
        """Test case for finetune_handler

        """
        pass

    def test_inference_deploy_handler(self) -> None:
        """Test case for inference_deploy_handler

        """
        pass

    def test_job_create_handler(self) -> None:
        """Test case for job_create_handler

        """
        pass


if __name__ == '__main__':
    unittest.main()
