# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.resource_task_status_resp import ResourceTaskStatusResp

class TestResourceTaskStatusResp(unittest.TestCase):
    """ResourceTaskStatusResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceTaskStatusResp:
        """Test ResourceTaskStatusResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceTaskStatusResp`
        """
        model = ResourceTaskStatusResp()
        if include_optional:
            return ResourceTaskStatusResp(
                data = [
                    openapi_client.models.resource_sync_task.ResourceSyncTask(
                        resource_id = '', 
                        resource_type = '', 
                        source = '', 
                        status = '', 
                        token = '', )
                    ],
                total = 56
            )
        else:
            return ResourceTaskStatusResp(
                data = [
                    openapi_client.models.resource_sync_task.ResourceSyncTask(
                        resource_id = '', 
                        resource_type = '', 
                        source = '', 
                        status = '', 
                        token = '', )
                    ],
                total = 56,
        )
        """

    def testResourceTaskStatusResp(self):
        """Test ResourceTaskStatusResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
