# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.node_add_resp import NodeAddResp

class TestNodeAddResp(unittest.TestCase):
    """NodeAddResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeAddResp:
        """Test NodeAddResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeAddResp`
        """
        model = NodeAddResp()
        if include_optional:
            return NodeAddResp(
                message = ''
            )
        else:
            return NodeAddResp(
                message = '',
        )
        """

    def testNodeAddResp(self):
        """Test NodeAddResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
