# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recharge_list_resp import RechargeListResp

class TestRechargeListResp(unittest.TestCase):
    """RechargeListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RechargeListResp:
        """Test RechargeListResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RechargeListResp`
        """
        model = RechargeListResp()
        if include_optional:
            return RechargeListResp(
                total = 56,
                data = [
                    openapi_client.models.user_recharge.UserRecharge(
                        id = 56, 
                        recharge_id = '', 
                        user_id = '', 
                        amount = 1.337, 
                        before_balance = 1.337, 
                        after_balance = 1.337, 
                        description = '', 
                        created_at = '', 
                        updated_at = '', )
                    ]
            )
        else:
            return RechargeListResp(
                total = 56,
                data = [
                    openapi_client.models.user_recharge.UserRecharge(
                        id = 56, 
                        recharge_id = '', 
                        user_id = '', 
                        amount = 1.337, 
                        before_balance = 1.337, 
                        after_balance = 1.337, 
                        description = '', 
                        created_at = '', 
                        updated_at = '', )
                    ],
        )
        """

    def testRechargeListResp(self):
        """Test RechargeListResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
