# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.billing_tasks_resp import BillingTasksResp

class TestBillingTasksResp(unittest.TestCase):
    """BillingTasksResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingTasksResp:
        """Test BillingTasksResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingTasksResp`
        """
        model = BillingTasksResp()
        if include_optional:
            return BillingTasksResp(
                data = [
                    openapi_client.models.task_billing.TaskBilling(
                        user_id = '', 
                        job_id = '', 
                        job_type = '', 
                        amount = 1.337, 
                        begin_time = '', 
                        end_time = '', )
                    ],
                total = 56
            )
        else:
            return BillingTasksResp(
                data = [
                    openapi_client.models.task_billing.TaskBilling(
                        user_id = '', 
                        job_id = '', 
                        job_type = '', 
                        amount = 1.337, 
                        begin_time = '', 
                        end_time = '', )
                    ],
                total = 56,
        )
        """

    def testBillingTasksResp(self):
        """Test BillingTasksResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
