# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.balance_get_req import BalanceGetReq

class TestBalanceGetReq(unittest.TestCase):
    """BalanceGetReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BalanceGetReq:
        """Test BalanceGetReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BalanceGetReq`
        """
        model = BalanceGetReq()
        if include_optional:
            return BalanceGetReq(
                user_id = ''
            )
        else:
            return BalanceGetReq(
                user_id = '',
        )
        """

    def testBalanceGetReq(self):
        """Test BalanceGetReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
