# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.jupyterlab_update_req import JupyterlabUpdateReq

class TestJupyterlabUpdateReq(unittest.TestCase):
    """JupyterlabUpdateReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JupyterlabUpdateReq:
        """Test JupyterlabUpdateReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JupyterlabUpdateReq`
        """
        model = JupyterlabUpdateReq()
        if include_optional:
            return JupyterlabUpdateReq(
                job_name = '',
                cpu_count = 56,
                memory = 56,
                gpu_count = 56,
                gpu_product = '',
                data_volume_size = 56
            )
        else:
            return JupyterlabUpdateReq(
                job_name = '',
                cpu_count = 56,
                memory = 56,
                gpu_count = 56,
                gpu_product = '',
                data_volume_size = 56,
        )
        """

    def testJupyterlabUpdateReq(self):
        """Test JupyterlabUpdateReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
