# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cluster_cpods_resp import ClusterCpodsResp

class TestClusterCpodsResp(unittest.TestCase):
    """ClusterCpodsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterCpodsResp:
        """Test ClusterCpodsResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterCpodsResp`
        """
        model = ClusterCpodsResp()
        if include_optional:
            return ClusterCpodsResp(
                data = [
                    openapi_client.models.cpod_info.CpodInfo(
                        cpod_id = '', 
                        cpod_version = '', 
                        node_name = '', 
                        gpu_vendor = '', 
                        gpu_prod = '', 
                        gpu_mem = 56, 
                        gpu_total = 56, 
                        gpu_allocatable = 56, 
                        create_time = '', 
                        update_time = '', )
                    ]
            )
        else:
            return ClusterCpodsResp(
                data = [
                    openapi_client.models.cpod_info.CpodInfo(
                        cpod_id = '', 
                        cpod_version = '', 
                        node_name = '', 
                        gpu_vendor = '', 
                        gpu_prod = '', 
                        gpu_mem = 56, 
                        gpu_total = 56, 
                        gpu_allocatable = 56, 
                        create_time = '', 
                        update_time = '', )
                    ],
        )
        """

    def testClusterCpodsResp(self):
        """Test ClusterCpodsResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
