# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.job_get_resp import JobGetResp

class TestJobGetResp(unittest.TestCase):
    """JobGetResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobGetResp:
        """Test JobGetResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobGetResp`
        """
        model = JobGetResp()
        if include_optional:
            return JobGetResp(
                content = [
                    openapi_client.models.job.Job(
                        ckpt_path = '', 
                        ckpt_vol = '', 
                        cpod_id = '', 
                        create_time = '', 
                        dataset_name = '', 
                        dataset_path = '', 
                        deleted = 56, 
                        gpu_number = 56, 
                        gpu_type = '', 
                        image_path = '', 
                        job_id = 56, 
                        job_name = '', 
                        job_type = '', 
                        json_all = '', 
                        model_path = '', 
                        model_vol = '', 
                        obtain_status = 56, 
                        pretrained_model_name = '', 
                        pretrained_model_path = '', 
                        run_command = '', 
                        stop_time = 56, 
                        stop_type = 56, 
                        update_time = '', 
                        user_id = '', 
                        work_status = 56, 
                        status = '', 
                        tensor_url = '', )
                    ],
                total_elements = 56
            )
        else:
            return JobGetResp(
                content = [
                    openapi_client.models.job.Job(
                        ckpt_path = '', 
                        ckpt_vol = '', 
                        cpod_id = '', 
                        create_time = '', 
                        dataset_name = '', 
                        dataset_path = '', 
                        deleted = 56, 
                        gpu_number = 56, 
                        gpu_type = '', 
                        image_path = '', 
                        job_id = 56, 
                        job_name = '', 
                        job_type = '', 
                        json_all = '', 
                        model_path = '', 
                        model_vol = '', 
                        obtain_status = 56, 
                        pretrained_model_name = '', 
                        pretrained_model_path = '', 
                        run_command = '', 
                        stop_time = 56, 
                        stop_type = 56, 
                        update_time = '', 
                        user_id = '', 
                        work_status = 56, 
                        status = '', 
                        tensor_url = '', )
                    ],
                total_elements = 56,
        )
        """

    def testJobGetResp(self):
        """Test JobGetResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
