# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sys_inference import SysInference

class TestSysInference(unittest.TestCase):
    """SysInference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SysInference:
        """Test SysInference
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SysInference`
        """
        model = SysInference()
        if include_optional:
            return SysInference(
                service_name = '',
                status = '',
                model_id = '',
                model_name = '',
                model_path = '',
                model_size = 56,
                model_is_public = True,
                model_template = '',
                model_meta = '',
                model_category = '',
                adapter_id = '',
                adapter_name = '',
                adapter_path = '',
                adapter_size = 56,
                adapter_is_public = True,
                url = '',
                api = '',
                gpu_model = '',
                gpu_count = 56,
                create_time = '',
                start_time = '',
                end_time = ''
            )
        else:
            return SysInference(
                service_name = '',
                status = '',
                url = '',
                api = '',
                gpu_model = '',
                gpu_count = 56,
                create_time = '',
                start_time = '',
                end_time = '',
        )
        """

    def testSysInference(self):
        """Test SysInference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
