# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.node_list_resp import NodeListResp

class TestNodeListResp(unittest.TestCase):
    """NodeListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeListResp:
        """Test NodeListResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeListResp`
        """
        model = NodeListResp()
        if include_optional:
            return NodeListResp(
                data = [
                    openapi_client.models.cluster_node_info.ClusterNodeInfo(
                        gpu_count = 56, 
                        gpu_product = '', 
                        name = '', 
                        role = [
                            ''
                            ], )
                    ]
            )
        else:
            return NodeListResp(
                data = [
                    openapi_client.models.cluster_node_info.ClusterNodeInfo(
                        gpu_count = 56, 
                        gpu_product = '', 
                        name = '', 
                        role = [
                            ''
                            ], )
                    ],
        )
        """

    def testNodeListResp(self):
        """Test NodeListResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
