# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.inference_service import InferenceService

class TestInferenceService(unittest.TestCase):
    """InferenceService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InferenceService:
        """Test InferenceService
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InferenceService`
        """
        model = InferenceService()
        if include_optional:
            return InferenceService(
                service_name = '',
                status = '',
                model_name = '',
                model_id = '',
                model_size = 56,
                model_is_public = True,
                model_category = '',
                model_meta = '',
                adapter_name = '',
                adapter_id = '',
                adapter_size = 56,
                adapter_is_public = True,
                gpu_type = '',
                gpu_number = 56,
                min_instances = 56,
                max_instances = 56,
                template = '',
                cpod_id = '',
                user_id = ''
            )
        else:
            return InferenceService(
                service_name = '',
                status = '',
                model_name = '',
                model_id = '',
                model_size = 56,
                model_is_public = True,
                model_category = '',
                model_meta = '',
                adapter_name = '',
                adapter_id = '',
                adapter_size = 56,
                adapter_is_public = True,
                gpu_type = '',
                gpu_number = 56,
                min_instances = 56,
                max_instances = 56,
                template = '',
                cpod_id = '',
                user_id = '',
        )
        """

    def testInferenceService(self):
        """Test InferenceService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
