# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_list_resp import AppListResp

class TestAppListResp(unittest.TestCase):
    """AppListResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppListResp:
        """Test AppListResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppListResp`
        """
        model = AppListResp()
        if include_optional:
            return AppListResp(
                data = [
                    openapi_client.models.app.App(
                        id = 56, 
                        app_id = '', 
                        app_name = '', 
                        user_id = '', 
                        desc = '', 
                        crd = '', 
                        status = 56, 
                        created_at = '', 
                        updated_at = '', )
                    ],
                total = 56
            )
        else:
            return AppListResp(
                data = [
                    openapi_client.models.app.App(
                        id = 56, 
                        app_id = '', 
                        app_name = '', 
                        user_id = '', 
                        desc = '', 
                        crd = '', 
                        status = 56, 
                        created_at = '', 
                        updated_at = '', )
                    ],
                total = 56,
        )
        """

    def testAppListResp(self):
        """Test AppListResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
