# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class AppJob(BaseModel):
    """
    AppJob
    """ # noqa: E501
    id: StrictInt
    job_name: StrictStr
    user_id: StrictStr = Field(description=" 用户ID")
    app_id: StrictStr = Field(description=" 应用ID")
    app_name: StrictStr = Field(description=" 应用名字")
    instance_name: StrictStr = Field(description=" 实例名称")
    cpod_id: StrictStr = Field(description=" cpod id")
    status: StrictStr = Field(description=" 状态")
    billing_status: StrictInt = Field(description=" 账单状态（0 未结清、1 已结清）")
    url: StrictStr = Field(description=" URL")
    start_time: StrictStr = Field(description=" 推理服务启动时间")
    end_time: StrictStr = Field(description=" 推理服务终止时间")
    created_at: StrictStr = Field(description=" 创建时间")
    updated_at: StrictStr = Field(description=" 更新时间")
    __properties: ClassVar[List[str]] = ["id", "job_name", "user_id", "app_id", "app_name", "instance_name", "cpod_id", "status", "billing_status", "url", "start_time", "end_time", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AppJob from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AppJob from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "job_name": obj.get("job_name"),
            "user_id": obj.get("user_id"),
            "app_id": obj.get("app_id"),
            "app_name": obj.get("app_name"),
            "instance_name": obj.get("instance_name"),
            "cpod_id": obj.get("cpod_id"),
            "status": obj.get("status"),
            "billing_status": obj.get("billing_status"),
            "url": obj.get("url"),
            "start_time": obj.get("start_time"),
            "end_time": obj.get("end_time"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


