# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class InferenceService(BaseModel):
    """
    InferenceService
    """ # noqa: E501
    service_name: StrictStr
    status: StrictStr
    model_name: StrictStr
    model_id: StrictStr
    model_size: StrictInt
    model_is_public: StrictBool
    model_category: StrictStr
    model_meta: StrictStr
    adapter_name: StrictStr
    adapter_id: StrictStr
    adapter_size: StrictInt
    adapter_is_public: StrictBool
    gpu_type: StrictStr
    gpu_number: StrictInt
    min_instances: StrictInt
    max_instances: StrictInt
    template: StrictStr
    cpod_id: StrictStr
    user_id: StrictStr
    __properties: ClassVar[List[str]] = ["service_name", "status", "model_name", "model_id", "model_size", "model_is_public", "model_category", "model_meta", "adapter_name", "adapter_id", "adapter_size", "adapter_is_public", "gpu_type", "gpu_number", "min_instances", "max_instances", "template", "cpod_id", "user_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InferenceService from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InferenceService from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "service_name": obj.get("service_name"),
            "status": obj.get("status"),
            "model_name": obj.get("model_name"),
            "model_id": obj.get("model_id"),
            "model_size": obj.get("model_size"),
            "model_is_public": obj.get("model_is_public"),
            "model_category": obj.get("model_category"),
            "model_meta": obj.get("model_meta"),
            "adapter_name": obj.get("adapter_name"),
            "adapter_id": obj.get("adapter_id"),
            "adapter_size": obj.get("adapter_size"),
            "adapter_is_public": obj.get("adapter_is_public"),
            "gpu_type": obj.get("gpu_type"),
            "gpu_number": obj.get("gpu_number"),
            "min_instances": obj.get("min_instances"),
            "max_instances": obj.get("max_instances"),
            "template": obj.get("template"),
            "cpod_id": obj.get("cpod_id"),
            "user_id": obj.get("user_id")
        })
        return _obj


