# coding: utf-8

"""
    调度器服务

    调度器服务的接口定义

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_client.models.cache import Cache
from openapi_client.models.gpu_summary import GPUSummary
from openapi_client.models.node_info import NodeInfo
from typing import Optional, Set
from typing_extensions import Self

class ResourceInfo(BaseModel):
    """
    ResourceInfo
    """ # noqa: E501
    gpu_summaries: List[GPUSummary]
    cpod_version: StrictStr
    nodes: List[NodeInfo]
    cpod_id: StrictStr
    caches: List[Cache]
    __properties: ClassVar[List[str]] = ["gpu_summaries", "cpod_version", "nodes", "cpod_id", "caches"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourceInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in gpu_summaries (list)
        _items = []
        if self.gpu_summaries:
            for _item_gpu_summaries in self.gpu_summaries:
                if _item_gpu_summaries:
                    _items.append(_item_gpu_summaries.to_dict())
            _dict['gpu_summaries'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item_nodes in self.nodes:
                if _item_nodes:
                    _items.append(_item_nodes.to_dict())
            _dict['nodes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in caches (list)
        _items = []
        if self.caches:
            for _item_caches in self.caches:
                if _item_caches:
                    _items.append(_item_caches.to_dict())
            _dict['caches'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourceInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gpu_summaries": [GPUSummary.from_dict(_item) for _item in obj["gpu_summaries"]] if obj.get("gpu_summaries") is not None else None,
            "cpod_version": obj.get("cpod_version"),
            "nodes": [NodeInfo.from_dict(_item) for _item in obj["nodes"]] if obj.get("nodes") is not None else None,
            "cpod_id": obj.get("cpod_id"),
            "caches": [Cache.from_dict(_item) for _item in obj["caches"]] if obj.get("caches") is not None else None
        })
        return _obj


