name: Test and Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # 根据需求调整 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine pytest
        # 如果有 requirements.txt 文件，优先使用
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # 如果有其他依赖未在 requirements.txt 中列出，可以手动安装
        pip install pydantic

    - name: Debug Environment (Optional)
      run: |
        python -m pip list
        which python

    - name: Run Tests
      run: pytest

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      if: success()
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
